// Generated by CoffeeScript 1.9.3
(function() {
  var cps;

  cps = require('../src/cps').cps;

  describe('cps', function() {
    it('works with unary functions', function() {
      var add1, cpsAdd1;
      add1 = function(x) {
        return x + 1;
      };
      cpsAdd1 = cps(add1);
      return expect(cpsAdd1(0)(function(x) {
        return x + 1;
      })).toEqual(2);
    });
    it('and binary functions', function() {
      var binaryFunction, cpsFun;
      binaryFunction = function(x, y) {
        return x + y;
      };
      cpsFun = cps(binaryFunction);
      return expect(cpsFun(1, 2)(function(x) {
        return x + 1;
      })).toEqual(4);
    });
    return it('and ternary functions', function() {
      var cpsFun, ternaryFunction;
      ternaryFunction = function(x, y, z) {
        return x + y + z;
      };
      cpsFun = cps(ternaryFunction);
      return expect(cpsFun(1, 2, 3)(function(x) {
        return x + 1;
      })).toEqual(7);
    });
  });

}).call(this);
