// Generated by CoffeeScript 1.9.3
(function() {
  var chain, cps, id,
    slice = [].slice;

  id = function(x) {
    return x;
  };

  cps = function(f) {
    return function() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      return function(h) {
        return h(f.apply(this, args));
      };
    };
  };

  chain = function() {
    var funcs;
    funcs = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    return function() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      return function(f) {
        return f(funcs.reduce(function(acc, func) {
          return acc = func(acc)(id);
        }, funcs.shift().apply(this, args)(id)));
      };
    };
  };

  module.exports = {
    cps: cps,
    chain: chain
  };

}).call(this);
