// Generated by CoffeeScript 1.9.3
(function() {
  var cps,
    slice = [].slice;

  exports.cps = cps = function(f) {
    return function() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      return function(h) {
        return h(f.apply(this, args));
      };
    };
  };

}).call(this);
